//leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

//Igiload
_igiload = execVM "IgiLoad\IgiLoadInit.sqf";

// HC Client Code
if(isNil "paramsArray") then{ paramsArray=[0,0,0]};

//get mission parameter to see if 
//HeadlessClient is present and assign its name
if(paramsArray select 0 == 1) then{
	if(isServer) then{
		HCPresent = true;
		publicVariable "HCPresent";
	};
	if (!hasInterface && !isServer) then{
        waitUntil{!isNull player};
		HCName = name player; 
		publicVariable "HCName";
	};
} else{
	if(isServer) then{
		HCPresent = false;
		HCName = "NONE";
		publicVariable "HCPresent";
		publicVariable "HCName";
	};
};

waitUntil{!isNil "HCPresent"};
waitUntil{!isNil "HCName"};

if(!isServer) then {waitUntil{!isNull player}};

//////////////////////////////////////
//////  Endtrigger  nur für S17  //////
//////////////////////////////////////
1 setRadioMsg "NULL";
2 setRadioMsg "NULL";
3 setRadioMsg "Null";
if(player==s17) then {
	1 setRadioMsg "ende";
	2 setRadioMsg "fallback";
	3 setRadioMsg "arti";
};


if (local player) then {
   player enableFatigue false;
   player addEventhandler ["Respawn", {player enableFatigue false}];
};

//Video
[] spawn {
waituntil {!isnil "bis_fnc_init"};
enableRadio false;
_camera = "camera" camCreate [(getPos player select 0),(getPos player select 1),200];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.700;
_camera camCommit 0;
waitUntil {camCommitted _camera};
cutText["Synchronisiere, bitte warten . . .", "BLACK FADED", 10];
waitUntil {time > 12};
cutText["", "BLACK IN", 0];
enableRadio true;
};